--DDL FOR DATAWAREHOUSE.BRONZE.CRM_CUST_INFO TABLE
CREATE OR REPLACE TABLE DATAWAREHOUSE.BRONZE.CRM_CUST_INFO (
    
    CST_ID INT,
    CST_KEY VARCHAR(25),
    CST_FIRSTNAME VARCHAR(25),
    CST_LASTNAME VARCHAR(25),
    CST_MARITAL_STATUS VARCHAR(25),
    CST_GNDR VARCHAR(10),
    CST_CREATE_DATE DATE
);

-- DDL FOR DATAWAREHOUSE.BRONZE.CRM_PRODUCT_INFO TABLE
CREATE OR REPLACE TABLE DATAWAREHOUSE.BRONZE.CRM_PRODUCT_INFO(
    PRD_ID INT,
    PRD_KEY VARCHAR(255),
    PRD_NM VARCHAR(255),
    PRD_COST INT,
    PRD_LINE VARCHAR(255),
    PRD_START_DATE DATE,
    PRD_END_DATE DATE
);

-- DDL FOR DATAWAREHOUSE.BRONZE.CRM_SALES_INFO TABLE
CREATE OR REPLACE TABLE DATAWAREHOUSE.BRONZE.CRM_SALES_INFO (

    SLS_ORD_NUM VARCHAR(25),
    SLS_PRD_KEY VARCHAR(25),
    SLA_CUST_ID VARCHAR(25),
    SLS_ORDER_DT DATE,
    SLS_SHIP_DT DATE,
    SLS_DUE_DT DATE,
    SLS_SALES INT,
    SLS_QUANTITY INT,
    SLS_PRICE INT
);


-- DDL FOR DATAWAREHOUSE.BRONZE.ERP_CUST_AZ12 TABLE
CREATE OR REPLACE TABLE DATAWAREHOUSE.BRONZE.ERP_CUST_AZ12(
    
    CID VARCHAR(255),
    BDATE DATE,
    GEN VARCHAR(25)
);


-- DDL FOR DATAWAREHOUSE.BRONZE.ERP_LOC_A101 TABLE
CREATE OR REPLACE TABLE DATAWAREHOUSE.BRONZE.ERP_LOC_A101(

    CID VARCHAR(255),
    CNTRY VARCHAR(255)
);

-- DDL FOR DATAWAREHOUSE.BRONZE.ERP_PX_CAT_G1V2 TABLE
CREATE OR REPLACE TABLE DATAWAREHOUSE.BRONZE.ERP_PX_CAT_G1V2(

    ID VARCHAR(255),
    CAT VARCHAR(255),
    SUBCAT VARCHAR(255),
    MAINTENANCE VARCHAR(255) 
);

-- CREATED A FILE FORMAT
CREATE FILE FORMAT DATAWAREHOUSE.BRONZE.FILE_FORMAT_CRM_CUST_INFO
  TYPE = 'CSV'
  FIELD_DELIMITER = ','
  SKIP_HEADER = 1
  TRIM_SPACE = TRUE
  EMPTY_FIELD_AS_NULL = TRUE
  NULL_IF = ('\\N', 'NULL');

-- CREATED A INTERNAL STAGE IN ORDER TO LOAD THE DATA FROM LOACL SYSTEM TO INTERNAL STAGE
CREATE OR REPLACE STAGE DATAWAREHOUSE.BRONZE.CRM_DATA
FILE_FORMAT = 'DATAWAREHOUSE.BRONZE.FILE_FORMAT_CRM_CUST_INFO'
COMMENT = 'THIS STAGE WILL STORE THE CRM SOURCE DATA'


-- USED PUT FILE COMMAND IN SNOWSQL IN ORDER TO LOAD THE DATA FROM LOCAL SYSTEM TO SNOWFLAKE STAGE
-- put file://C:\Users\rajsi\Downloads\sql-data-warehouse-project\sql-data-warehouse-project\datasets\source_erp\CUST_AZ12.csv @CRM_DATA;
